FROM openjdk:8-jdk-alpine
EXPOSE 8080
ADD demo-docker-rest-api/target/demo-docker-rest-api-0.0.1-SNAPSHOT.jar demo-docker-rest-api-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","demo-docker-rest-api-0.0.1-SNAPSHOT.jar"]
 